# -*- python -*-
import os
import lsst.sconsUtils

env = lsst.sconsUtils.env.Clone()
tests = lsst.sconsUtils.scripts.BasicSConscript.tests(
    pySingles=['nopytest_test_processCcd.py'],
    pyList=[],
)

env.Depends(tests, "../decam/linearizer")

if "DAF_BUTLER_PLUGINS" in os.environ:
    lsst.sconsUtils.env["ENV"]["DAF_BUTLER_PLUGINS"] = os.environ["DAF_BUTLER_PLUGINS"]
