# -*- python -*-
import os
import lsst.sconsUtils

env = lsst.sconsUtils.env.Clone()
tests = lsst.sconsUtils.scripts.BasicSConscript.tests(pyList=[])

env.Depends(tests, "../decam/linearizer")
env.Depends(tests, "../decam/crosstalk")

if "DAF_BUTLER_PLUGINS" in os.environ:
    lsst.sconsUtils.env["ENV"]["DAF_BUTLER_PLUGINS"] = os.environ["DAF_BUTLER_PLUGINS"]
